name: Deploy to Koyeb
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**'
    - 'lists/**'
    - '*.txt'
    - '*.yaml'
    - '*.conf'
    - '*.txt'
    - '*.sh'
    - '*.py'
    - 'README.md'
  schedule:
    - cron: '15 17 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/anT0ny54/mosdns-docker:latest
       docker run ghcr.io/anT0ny54/mosdns-docker:latest
       docker push ghcr.io/anT0ny54/mosdns-docker:latest
        
