name: sync readme

on:
  workflow_dispatch:
  push:
    paths:
      - "README.md"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Sync
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME1 }}
        password: ${{ secrets.DOCKERHUB_TOKEN1 }}
        repository: ${{ secrets.DOCKERHUB_USERNAME1 }}/mosdns1
        readme: "./README.md"
